-- Project generated by script.
-- Date: Ter,06/11/2012-10:06:36
-- Author: rogerio
-- Comments: Entity Description: xor2.
 
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
 
entity xor2 is
	port (x, y: in std_logic; z: out std_logic);
end xor2;
 
architecture logica of xor2 is
begin
  -- Commands.
   z <= x xor y;
end logica;
